#!/bin/sh

array=(john0 john1 john3 john4 john5 john6 john10 john11)
comm="java -cp resources:classes Main"

for i in "${!array[@]}"; do
  echo 'cd entities;'"java -cp resources:classes Main $i"
  ssh "${array[$i]}" 'cd entities;'"java -cp resources:classes Main $i" &
done


